#!/bin/python
import qrcode
import os,sys
from subprocess import run
red = "\033[1;31m"     
green = "\033[1;32m"   
yellow = "\033[1;33m"
purple = "\033[1;34m"
pink = "\033[1;35m"
blue = "\033[1;36m"
white = "\033[1;37m"
black = "\033[1;30m"
Gold = "\033[38;5;220m"
Pink = "\033[38;5;206m"
Purple = "\033[38;5;93m"
DarkGreen = "\033[38;5;28m"
Orange = "\033[38;5;208m"
SkyBlue = "\033[38;5;111m"
Teal = "\033[38;5;37m"
R = "\033[91m"
G = "\033[92m"
Y = "\033[93m"
PU = "\033[94m"
PI = "\033[95m"
B = "\033[96m"
W = "\033[97m"
BL = "\033[80m"
RESET = "\033[0m"
os.system("clear")
print("")
print("\033[1;32m")
print("\t░██████╗░██████╗░░█████╗░░█████╗░██████╗░███████╗")
print("\t██╔═══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝")
print("\t██║██╗██║██████╔╝██║░░╚═╝██║░░██║██║░░██║█████╗░░")
print("\t╚██████╔╝██╔══██╗██║░░██╗██║░░██║██║░░██║██╔══╝░░")
print("\t░╚═██╔═╝░██║░░██║╚█████╔╝╚█████╔╝██████╔╝███████╗")
print("\t░░░╚═╝░░░╚═╝░░╚═╝░╚════╝░░╚════╝░╚═════╝░╚══════╝\n")
text = f"\t\t{Pink}Code {W}By {SkyBlue}Manjunath\n\n"
print(text + RESET)
print((yellow)+"\t\t1. Website Qrcode\n")
print((pink)+"\t\t2. Phone Number Qrcode\n")
print((green)+"\t\t3. WiFi Qrcode\n\n")
print("\033[38;5;220m")

choice = input("Enter Your Choice ────► ")
if choice == "1":
    print ("\033[38;5;93m")
    website_url = input("Enter the website URL: ")
    image_name = input("Enter the image name : ")

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(website_url)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    img.save(f"{image_name}.png")
    print((G)+f"QR code for the website URL saved as {image_name}.png\n")

elif choice == "2":
    print ("\033[38;5;206m")
    phone_number = input("Enter the phone number and country code: ")
    image_name = input("Enter the image name : ")

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(f"tel:{phone_number}")
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    img.save(f"{image_name}.png")
    print((G)+f"QR code for the phone number saved as {image_name}.png\n")

elif choice == "3":
    print ("\033[1;32m")
    ssid = input("Enter the WiFi SSID: ")
    password = input("Enter the WiFi password: ")
    image_name = input("Enter the image name : ")
    wifi_data = f"WIFI:S:{ssid};T:WPA;P:{password};;"

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(wifi_data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    img.save(f"{image_name}.png")
    print((G)+f"QR code for the WiFi saved as {image_name}.png\n")

else:
    print((R)+"Invalid choice. Please select a valid option (1-3)...\n")
